# languages
bash:
  - "**/*.sh"
  - "**/Makefile"
golang:
  - "**/*.go"
  - "**/go.*"
js:
  - "web/**/*"
  - "**/*.js"
  - "**/*.json"
  - "**/*.vue"
docker:
  - "**/Dockerfile"
  - "**/Dockerfile.*"
  - "**/docker-compose.*"
kubernetes:
  - "kubernetes/**/*"
  - "k8s/**/*"
  - "charts/**/*"
  - "helm/**/*"
terraform:
  - "terraform/**/*"
  - "tfk8s/**/*"
  - "**/*.tf"
  - "helm/**/*"


# scope
dev:
  - "cmd/**/*"
  - "internal/**/*"
  - "pkg/**/*"
  - "web/**/*"
ops:
  - "build/**/*"
  - "deploy/**/*"
  - "scripts/**/*"
cicd:
  - ".github/**/*.yml"
doc:
  - "**/*.md"
  - "**/*.txt"
  - "assets/**/*"

