version: "3.8"

services:
  api:
    container_name: go-yave_api
    build:
      context: .
      dockerfile: build/package/api/Dockerfile
      target: dev_build
    ports:
      - 3334:3334
    volumes:
      - ./:/go/src/github.com/blyndusk/go-yave/
    networks:
      - main

  postgres:
    container_name: go-yave_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
      - DATABASE_HOST=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - main

  adminer:
    container_name: go-yave_adminer
    build:
      context: .
      dockerfile: build/package/adminer/Dockerfile
    environment:
      ADMINER_DB: db
      ADMINER_DRIVER: pgsql
      ADMINER_PASSWORD: root
      ADMINER_SERVER: postgres
      ADMINER_USERNAME: root
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: Sample DB
    restart: always
    ports:
      - 3334:8080
    depends_on:
      - postgres
    networks:
      - main

volumes:
  postgres:

networks:
  main:
