name: DOCKER

on:
  push:
    branches:
      - main

jobs:
  DOCKER:
    name: DOCKER
    runs-on: ubuntu-latest
    steps:

      - name: 1 - SETUP BUILDX
        uses: docker/setup-buildx-action@v1

      - name: 2 - LOGIN TO GHCR.IO
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 3 - BUILD + PUSH
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: .docker/api/prod.Dockerfile
          tags: ghcr.io/blyndusk/repo-template_api:latest

      - name: 4 - IMAGE DIGEST
        run: echo ${{ steps.docker_build.outputs.digest }}
