name: GO

on: [push]

jobs:
  GO:
    name: GO
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    steps:
      # checkout to current workspace
    - name: 1 - CHECKOUT
      uses: actions/checkout@v2

      # install golang with specific version
    - name: 2 - SETUP GO@1.15
      uses:  actions/setup-go@v1
      with:
          go-version: 1.15

      # lint files before build using gofmt
    - name: 3 - LINT
      run: |
        gofmt -e -l -s -w .
    
      # build the project (in the api/ folder L11)
    - name: 4 - BUILD
      run: |
        go build -v ./...